  language: python
  python:
    - 3.6
    - nightly
  before_install:
    - pip install awscli
    - export PATH=$PATH:$HOME/.local/bin # put aws in the path
    - export AWS_ACCESS_KEY_ID=$aws_access_key
    - export AWS_SECRET_ACCESS_KEY=$aws_secret_access_key
    - export AWS_DEFAULT_REGION=$aws_region
    - echo $AWS_DEFAULT_REGION
    - eval which aws
  install:
    - pip install requests
    - pip install pytest-cov
  script:
    - cd lambda_func && python -m pytest --cov=.
    - cd api_testing && python -m pytest --cov=.
  deploy:
    - provider: lambda
      function_name: "LibbyDevelop"
      region: $aws_region
      role: "arn:aws:iam::263893614267:role/service-role/jerryTriviaIrelandRole"
      runtime: "python3.6"
      handler_name: "lambda_handler"
      module_name: "main_handler"
      access_key_id: $aws_access_key
      secret_access_key: $aws_secret_access_key
      zip: "${TRAVIS_BUILD_DIR}/lambda_func"
      on:
        branch: develop
    - provider: lambda
      function_name: "Libby"
      region: $aws_region
      role: "arn:aws:iam::263893614267:role/service-role/jerryTriviaIrelandRole"
      runtime: "python3.6"
      handler_name: "lambda_handler"
      module_name: "main_handler"
      access_key_id: $aws_access_key
      secret_access_key: $aws_secret_access_key
      zip: "${TRAVIS_BUILD_DIR}/lambda_func"
      on:
        branch: master
