  language: python
  python:
    - 3.6
    - nightly
  before_install:
    - pip install awscli
    - export PATH=$PATH:$HOME/.local/bin # put aws in the path
    - export AWS_ACCESS_KEY_ID=$aws_access_key
    - export AWS_SECRET_ACCESS_KEY=$aws_secret_access_key
    - export AWS_DEFAULT_REGION=$aws_region
    - echo $AWS_DEFAULT_REGION
    - eval which aws
  install:
    - pip install requests
  script:
    - cd api_testing/pytest && python api_testing_test.py
    - cd ../../lambda_func/pytest && python weather_test.py
  deploy:
    # deploy develop to the staging environment
    provider: script
    script:
      - cd ../lambda_func
      - zip -r ../deploy.zip .
      - cd ..
      - aws lambda update-function-code --function-name tuomasTestFunction --zip-file fileb://deploy.zip
    on:
        branch: develop
