  language: python
  python:
    - 3.6
    - nightly
  before_install:
    - pip install awscli
    - eval export AWS_ACCESS_KEY_ID=aws_access_key
    - eval export AWS_SECRET_ACCESS_KEY=aws_secret_access_key
    - eval export AWS_DEFAULT_REGION=aws_region
  install:
    - pip install requests
  script:
    - cd api_testing/pytest && python api_testing_test.py
    - cd ../../lambda_func/pytest && python weather_test.py
	deploy:
  	# deploy develop to the staging environment
  	- provider: script
    	script: scripts/deploy.sh
    	on:
      	branch: develop
