  language: python
  python:
    - 3.6
    - nightly
  install:
    - pip install requests
  script:
#    - cd api_testing/pytest && python api_testing_test.py
#    - cd ../lambda_func/pytest && python weather_test.py
    - python api_testing/pytest/api_testing_test.py
    - python lambda_func/pytest/weather_test.py
